project:
  type: website

website:
  title: "Gigi Mordock"
  navbar:
    left:
      - href: Project.qmd
        text: Project
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mainfont: times-new-roman
    fontsize: 20px

editor: visual

