project:
  type: website
  output-dir: docs
  render: 
  - index.qmd
  - Project.qmd

website:
  title: "Gigi Mordock"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: Project.qmd
        text: Project
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mainfont: times-new-roman
    fontsize: 20px

editor: visual

